import 'package:flutter/material.dart';

const kMainColor = Color(0XFFFFC12F);
const kSecondaryColor = Color(0XFFFFE6AC);
const kUnActiveColor = Color(0xFFC1BDB8);
const kProductName = 'ProductName';
const kProductPrice = 'ProductPrice';
const kProductCategory = 'ProductCategory';
const kProductLocation = 'ProductLocation';
const kProductDescription = 'ProductDescription';
const kProductsCollection = 'Products';
const kJackets = 'jackets';
const kTshirts = 'Tshirts';
const kTrousers = 'Trousers';
const kShoes = 'Shoes';
const kOrders = 'Orders';
const kOrderDetails = 'OrderDetails';
const kTotallPrice = 'TotallPrice';
const kAddress = 'Address';
const kProductQuantity = 'Quantity';
const kKeepMeLoggedIn = 'KeepMeLoggedIn';
